services:
  minio:
    container_name: minio_storage
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpassword
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  minio-data:

# docker exec -it minio_storage mc alias set myminio http://localhost:9000 root rootpassword
# docker exec -it minio_storage mc mb myminio/music
# docker exec -it minio_storage mc anonymous set public myminio/music
